#!/bin/bash

#SBATCH -J fastq_dump                      # Job name
#SBATCH -o qsub_job.log                    # Name of the stdout output file
#SBATCH -e qsub_job.log                    # Name of the stderr error file
#SBATCH --mail-user=your.name@my.utsa.edu  # Send me an email when you are done
#SBATCH --mail-type=ALL
#SBATCH -t 72:00:00                        # Time of job
#SBATCH -p compute1                        # Queue (partition) name
#SBATCH -N 1                               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1                               # Total # of mpi tasks (should be 1 for serial)

# Load one of these
module load ncbi/sratoolkit/2.11.0


fastq-dump -O /work/abc123/RNA_seq --split-files SRR10768940
fastq-dump -O /work/abc123/RNA_seq --split-files SRR10768941
fastq-dump -O /work/abc123/RNA_seq --split-files SRR10768942
fastq-dump -O /work/abc123/RNA_seq SRR8689518
fastq-dump -O /work/abc123/RNA_seq SRR8689519
fastq-dump -O /work/abc123/RNA_seq SRR8689520



exit
