#!/bin/bash

#SBATCH -J fastq_dump                      # Job name
#SBATCH -o qsub_job.log                    # Name of the stdout output file
#SBATCH -e qsub_job.log                    # Name of the stderr error file
#SBATCH --mail-user=your.name@my.utsa.edu  # Send me an email when you are done
#SBATCH --mail-type=ALL
#SBATCH -t 72:00:00                        # Time of job
#SBATCH -p compute1                        # Queue (partition) name
#SBATCH -N 1                               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1                               # Total # of mpi tasks (should be 1 for serial)

# Load one of these
module load R/3.5.1

cd /work/abc123/RNA_seq

Rscript RNA_seq_diff_exp5-24-21_mm39.R

exit
