#!/bin/bash -l

#SBATCH -J Rsubread
#SBATCH -o Rsubread.log
#SBATCH -e Rsubread.log
#SBATCH --mail-user your.name@my.utsa.edu
#SBATCH --mail-type=ALL
#SBATCH -t 72:00:00
#SBATCH -p normal
#SBATCH --ntasks=1
#SBATCH --partition=defq
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1

. /etc/profile.d/modules.sh
# Load one of these
module load R/3.5.1

cd /work/abc123/RNA_seq

Rscript RNA_seq_diff_exp5-24-21_mm39.R

exit
